# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.CharField(max_length=256, verbose_name='内容')),
                ('PV_num', models.BigIntegerField(default=0, verbose_name='统计量')),
                ('status', models.CharField(choices=[('有效', 'publish'), ('无效', 'private'), ('已删除', 'deleted')], default='有效', max_length=10, verbose_name='状态')),
                ('creator', models.CharField(max_length=100, verbose_name='创建人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
        ),
    ]
