# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eqp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_box_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('process', models.CharField(choices=[('0', '进站'), ('1', '出站'), ('2', 'pending')], default='0', max_length=32, verbose_name='进出站状态')),
                ('box_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_box', verbose_name='料盒ID')),
                ('eqp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_eqp', verbose_name='设备ID')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_operator',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('operator_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('operator_gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='1', max_length=1, verbose_name='性别')),
                ('operator_age', models.CharField(default=20, max_length=4, verbose_name='年龄')),
                ('operator_status', models.CharField(choices=[('Normal', '正常工作'), ('Dimission', '离职'), ('Deleted', '已删除')], default='Normal', max_length=32, verbose_name='状态')),
                ('usual_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_station', verbose_name='工作站点')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
    ]
