# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_box',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('box_id', models.AutoField(primary_key=True, serialize=False, verbose_name='料盒ID')),
                ('box_name', models.CharField(max_length=32, verbose_name='料盒名称')),
                ('box_capacity', models.BigIntegerField(default=50)),
                ('box_description', models.CharField(max_length=100, verbose_name='料盒描述')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_eqp',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('eqp_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='设备编号')),
                ('eqp_name_en', models.CharField(max_length=32, verbose_name='设备名称(英文)')),
                ('eqp_name_cn', models.CharField(max_length=32, verbose_name='设备名称(中文)')),
                ('eqp_status', models.TextField(max_length=128, verbose_name='设备状况')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_qr_code',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_content', models.CharField(max_length=128, verbose_name='标识内容')),
                ('qr_use', models.CharField(choices=[('Box', '料盒'), ('Batch', '批次号')], default='Box', max_length=32, verbose_name='用途')),
                ('qr_kind', models.CharField(choices=[('1', '一维码'), ('2', '二维码')], default='2', max_length=32, verbose_name='种类')),
                ('qr_description', models.CharField(max_length=128, verbose_name='备注')),
                ('qr_status', models.CharField(choices=[('Valid', '有效'), ('Invalid', '失效'), ('Pending', '待定'), ('Deleted', '已删除')], default='Valid', max_length=32, verbose_name='状态')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_station',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('station_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='站点ID')),
                ('station_name_en', models.CharField(max_length=32, verbose_name='站点名称(英文)')),
                ('station_name_cn', models.CharField(max_length=32, verbose_name='站点名称(中文)')),
                ('station_desc', models.CharField(max_length=100, verbose_name='站点描述')),
                ('station_seq', models.CharField(max_length=32, verbose_name='站点顺序')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.AddField(
            model_name='tbl_qr_code',
            name='qr_create_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_station', verbose_name='生码站点'),
        ),
        migrations.AddField(
            model_name='tbl_eqp',
            name='eqp_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_station'),
        ),
        migrations.AddField(
            model_name='tbl_box',
            name='box_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_qr_code', verbose_name='料盒ID'),
        ),
    ]
