# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eqp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_flow',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('flow_uuid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('flow_version', models.CharField(max_length=100, verbose_name='工作流版本')),
                ('current_eqp', models.CharField(max_length=32, verbose_name='当前站')),
                ('parent_eqp', models.CharField(max_length=32, verbose_name='父站')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_technology',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('tec_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_id', models.CharField(max_length=100, verbose_name='参数编号')),
                ('para_name', models.CharField(max_length=100, verbose_name='参数名')),
                ('para_value', models.CharField(max_length=100, verbose_name='设定值')),
                ('para_unit', models.CharField(max_length=100, verbose_name='单位')),
                ('eqp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqp.tbl_eqp')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
    ]
