# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_spc_standard',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('spc_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='SPC ID')),
                ('spc_kind', models.CharField(max_length=32, verbose_name='SPC种类')),
                ('spc_name', models.CharField(max_length=32, verbose_name='SPC名称')),
                ('spc_value', models.CharField(default=0, max_length=32, verbose_name='SPC值')),
                ('spc_unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('ml/s', 'ml/s'), ('C', 'C')], max_length=32, verbose_name='SPC单位')),
                ('spc_note', models.CharField(max_length=128, verbose_name='SPC备注')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
        migrations.CreateModel(
            name='tbl_spc_test',
            fields=[
                ('creator', models.CharField(default='admin', max_length=32, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.CharField(default='admin', max_length=32, verbose_name='最后更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('spc_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='SPC ID')),
                ('spc_kind', models.CharField(max_length=32, verbose_name='SPC种类')),
                ('spc_name', models.CharField(max_length=32, verbose_name='SPC名称')),
                ('spc_value', models.CharField(default=0, max_length=32, verbose_name='SPC测试值')),
                ('spc_unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('ml/s', 'ml/s'), ('C', 'C')], max_length=32, verbose_name='SPC单位')),
                ('spc_note', models.CharField(max_length=128, verbose_name='SPC备注')),
            ],
            options={
                'abstract': False,
                'ordering': ('update_time',),
            },
        ),
    ]
